"""Create initial schema

Revision ID: 2c81757f23b8
Revises:
Create Date: 2026-09-15 13:22:38.776910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2c81757f23b8"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Board",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("icon", sa.Text(), server_default="rocket", nullable=False),
        sa.Column(
            "createdAt",
            postgresql.TIMESTAMP(precision=3),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updatedAt", postgresql.TIMESTAMP(precision=3), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "Task",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("todo", "in_progress", "done", name="TaskStatus"),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", name="TaskPriority"),
            nullable=False,
        ),
        sa.Column("dueDate", sa.Text(), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("boardId", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["boardId"], ["Board.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("Task")
    op.drop_table("Board")

    postgresql.ENUM(name="TaskPriority").drop(
        op.get_bind(),
        checkfirst=True,
    )
    postgresql.ENUM(name="TaskStatus").drop(
        op.get_bind(),
        checkfirst=True,
    )
    # ### end Alembic commands ###
