"""add user ownership

Revision ID: 72404827cee4
Revises: 658f299e5127
Create Date: 2026-09-30 14:11:15.404061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72404827cee4'
down_revision: Union[str, Sequence[str], None] = '658f299e5127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=3), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('boards', sa.Column('user_id', sa.Text(), nullable=False))
    op.create_foreign_key('boards_user_id_fkey', 'boards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('boards_user_id_fkey', 'boards', type_='foreignkey')
    op.drop_column('boards', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
